import Header from "@/app/restaurant/components/Header";
import RestaurantNav from "@/app/restaurant/components/RestaurantNav";
import Menu from "@/app/restaurant/components/Menu";


export const metadata = {
    title: 'Menu | Test Restaurant | OpenTable',
    description: 'Generated by create next app',
}
export default function RestaurantMenu() {
    return (
        <>
            <Header/>
            <div className="flex m-auto w-2/3 justify-between items-start 0 -mt-11">
                <div className="bg-white w-[100%] rounded p-3 shadow">
                    <RestaurantNav/>
                    <Menu/>
                </div>
            </div>
            {/* DESCRIPTION PORTION */}
        </>
    )
}