import Header from "@/app/restaurant/components/Header";
import RestaurantNav from "@/app/restaurant/components/RestaurantNav";
import Menu from "@/app/restaurant/components/Menu";


export const metadata = {
    title: 'Menu | Test Restaurant | OpenTable',
    description: 'Generated by create next app',
}
export default function RestaurantMenu() {
    return (
        <>
            <div className="bg-white w-[100%] rounded p-3 shadow">
                <RestaurantNav/>
                <Menu/>
            </div>
        </>
    )
}