import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <main className={'bg-gray-100 min-h-screen w-screen'}>
        <NavBar />
        {children}
      </main>
      </body>
    </html>
  )
}
