import {Inter} from 'next/font/google'
import Header from "@/components/Header";
import RestaurantCard from "@/components/RestaurantCard";
import {PrismaClient} from "@prisma/client";

const prisma = new PrismaClient();

const fetchRestaurants = async () => {
    const restaurants = await prisma.restaurant.findMany();

    return restaurants
}


export const metadata = {
    title: 'Home | OpenTable',
    description: 'Generated by create next app',
}

const inter = Inter({subsets: ['latin']})

export default async function Home() {
    const restaurants = await fetchRestaurants();

    console.log({restaurants})
  return (
      <>
        <main>
          <Header />
          <div className="py-3 px-36 mt-10 flex flex-wrap justify-center">
            <RestaurantCard />
          </div>
        </main>
      </>
  )
}
