import Header from "@/app/search/components/Header";
import SideBar from "@/app/search/components/SideBar";
import RestaurantCard from "@/app/search/components/RestaurantCard";
import {PrismaClient} from "@prisma/client";
import {RestaurantCardType} from "@/app/page";
import RestaurantNav from "@/app/restaurant/components/RestaurantNav";

const prisma = new PrismaClient();

export const metadata = {
    title: 'Search Results | OpenTable',
    description: 'Generated by create next app',
}

const fetchRestaurantsByLocation = async (city: string | undefined) => {
    const select = {
        id: true,
            name: true,
            main_image: true,
            slug: true,
            price: true,
            location: true,
            cuisine: true,
    };

    if(!city) return prisma.restaurant.findMany({select: select});

    return prisma.restaurant.findMany({
        where: {
            location: {
                name: {
                    equals: city
                }
            }
        },
        select: select
    });
}

const fetchCities = async () => {
    const cities = await prisma.location.findMany();

    return cities;
}

const fetchCuisines = async () => {
    const cuisines = await prisma.cuisine.findMany();

    return cuisines;
}

export default async function Search({searchParams}: {searchParams: { city: string}}) {
    const restaurants = await fetchRestaurantsByLocation(searchParams.city.toLowerCase());
    const cities = await fetchCities();
    const cuisines = await fetchCuisines();
    return (
        <>
            <Header/>
            <div className="flex py-4 m-auto w-2/3 justify-between items-start">
                <SideBar cities={cities} cuisines={cuisines}/>
                <div className="w-5/6">
                    {restaurants.length ?
                        restaurants.map((restaurant) => (
                                <RestaurantCard restaurant={restaurant}/>
                            ))
                        :
                        <p>Sorry no restaurants found.</p>
                    }
                </div>
            </div>
        </>
    )
}