import Header from "@/app/search/components/Header";
import SideBar from "@/app/search/components/SideBar";
import RestaurantCard from "@/app/search/components/RestaurantCard";


export const metadata = {
    title: 'Search Results | OpenTable',
    description: 'Generated by create next app',
}

export default function Search() {
    return (
        <>
            <Header/>
            <div className="flex py-4 m-auto w-2/3 justify-between items-start">
                <SideBar/>
                <div className="w-5/6">
                    <RestaurantCard/>
                </div>
            </div>
        </>
    )
}